services:
  app:
    image: 192.168.31.233:5000/releasenojutsu:latest
    container_name: releasenojutsu
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
    restart: always
    env_file:
      - ./.env
    user: 1000:1000
